name: BetterSleeping
author: vallas
version: 3.0.0
api-version: "1.13"
main: be.dezijwegel.BetterSleeping
description: A plugin that makes sleeping in multiplayer fun again!
softdepend: [Essentials, PlaceholderAPI]
commands:
    bettersleeping:
        description: See all BetterSleeping commands
        usage: Perform /bettersleeping help or /bs help to see a list of commands!
        default: true
        aliases: [bs]
permissions:
    bettersleeping.*:
        description: Gives access to all BetterSleeping commands (/bs skip not included so you may want to add acces through bettersleeping.bypass)
        children:
            bettersleeping.help: true
            bettersleeping.reload: true
            bettersleeping.status: true
            bettersleeping.help.user: true
            bettersleeping.help.admin: true
            bettersleeping.night: true
    bettersleeping.reload:
        description: Gives access to /bs reload, which will reload the BetterSleeping config files
        default: op
    bettersleeping.status:
        description: Gives access to /bs status or /bs s, which will display info about the sleeping players
        default: true
    bettersleeping.bypass:
        description: Gives access to /bs skip, and this player will be ignored from the required player count
        default: false
    bettersleeping.help.admin:
        description: Gives access to /bs help, which will give info about all commands the user has access to and permission nodes will be shown as well
        default: op
    bettersleeping.help.user:
        description: Gives access to /bs help, which will give info about all commands a user has access to
        default: true
    bettersleeping.night:
        description: Gives access to /bs night or /bs n, which will disable night skipping for a while (see config.yml)
        default: op