sleeper_counter: "percentage"
percentage:
  needed: 30
absolute:
  needed: 2
mode: "smooth"
smooth:
  base_speedup: 60
  speedup_per_player: 10
  max_speedup: 500
setter:
  delay: 3
bed_enter_delay: 10
world_settings:
  worldname:
    enabled: true