# ____       _   _            _____ _                 _                       ____
#|  _ \     | | | |          / ____| |               (_)                     |___ \
#| |_) | ___| |_| |_ ___ _ _| (___ | | ___  ___ _ __  _ _ __   __ _     __   ____) |
#|  _ < / _ \ __| __/ _ \ '__\___ \| |/ _ \/ _ \ '_ \| | '_ \ / _` |    \ \ / /__ <
#| |_) |  __/ |_| ||  __/ |  ____) | |  __/  __/ |_) | | | | | (_| |     \ V /___) |
#|____/ \___|\__|\__\___|_| |_____/|_|\___|\___| .__/|_|_| |_|\__, |      \_/|____/
#                                              | |             __/ |
#                                              |_|            |___/


# To reset a BetterSleeping config file, you can simply delete it and perform /bs reload or restart the server

# Configuration guide and default values:       https://github.com/Nuytemans-Dieter/BetterSleeping/blob/v3.0.0/src/main/resources/sleeping_settings.yml
# All default config files can be found here:   https://github.com/Nuytemans-Dieter/BetterSleeping/blob/v3.0.0/src/main/resources

# Choose an option from below (percentage or absolute)
# With percentage, a relative amount of players needs to sleep (eg. needed: 30 -> 13 online players, 30% of 13 is 3,9. Will be rounded to the nearest number -> 4 sleeping players needed)
# With absolute, a set amount of players needs to sleep (eg. needed: 2 -> any amount of online players, 2 players need to sleep)
sleeper_counter: {sleeper_counter}

# This depends on your sleeper_counter setting
#     Percentage: This value is the percentage of players in a world that must sleep ([0, 100])
#     Absolute: This value is always the amount of players that must sleep, does not scale with the amount of online players!
needed: {needed}

# The duration (in seconds) of the night when enough players are sleeping
# Set this to 0 to skip the night instantly
# A normal night lasts 500 ticks
night_skip_length: {night_skip_length}

# Whether to start skipping the night
# Currently not possible:
#allow_partial_skipping: {allow_partial_skipping}

# The normal length of the day and night when not skipping (in seconds)
# This allows you to speed up or slow down the time
# Default: 700
day_length: {day_length}
# Default: 500
night_length: {night_length}

# The normal length of the day (in seconds)
# This allows you to speed up or slow down the time during nighttime
# Default: 700


# The time in seconds that players need to wait before they can enter the bed again after leaving it
bed_enter_cooldown: {bed_enter_delay}

# Disable BetterSleeping in certain worlds. This option is case sensitive!
# Sleeping is always enabled in worlds that are not in this list
world_settings:
  worldname:
    enabled: {world_settings.worldname.enabled}